modules:
- import: go.linka.cloud/protoautoindex
  repository: github.com/linka-cloud/proto-auto-index
  readme: https://raw.githubusercontent.com/linka-cloud/proto-auto-index/main/README.md
- import: go.linka.cloud/reconcile
  repository: github.com/linka-cloud/reconcile
  readme: https://raw.githubusercontent.com/linka-cloud/reconcile/master/README.md
- import: go.linka.cloud/libkv
  repository: github.com/linka-cloud/libkv
  readme: https://raw.githubusercontent.com/linka-cloud/libkv/master/README.md
- import: go.linka.cloud/pubsub
  repository: github.com/linka-cloud/pubsub
  readme: https://raw.githubusercontent.com/linka-cloud/pubsub/main/README.md
- import: go.linka.cloud/wirego
  repository: github.com/linka-cloud/wirego
  readme: https://raw.githubusercontent.com/linka-cloud/wirego/main/README.md
- import: go.linka.cloud/wireguard
  repository: github.com/linka-cloud/wireguard-old
  readme: https://raw.githubusercontent.com/linka-cloud/wireguard-old/api/README.md
- import: go.linka.cloud/router
  repository: github.com/linka-cloud/router
  readme: https://raw.githubusercontent.com/linka-cloud/router/master/README.md
- import: go.linka.cloud/healthcheck
  repository: github.com/linka-cloud/healthcheck
  readme: https://raw.githubusercontent.com/linka-cloud/healthcheck/master/README.md
- import: go.linka.cloud/k8s/dns
  repository: github.com/linka-cloud/k8s-dns-manager
  readme: https://raw.githubusercontent.com/linka-cloud/k8s-dns-manager/master/README.md
- import: go.linka.cloud/k8s/cert-manager-webhook-k8s-dns
  repository: github.com/linka-cloud/k8s/cert-manager-webhook-k8s-dns
  readme: https://raw.githubusercontent.com/linka-cloud/cert-manager-webhook-k8s-dns/master/README.md
- import: go.linka.cloud/k8s/lb
  repository: github.com/linka-cloud/k8s-lb
  readme: https://raw.githubusercontent.com/linka-cloud/k8s-lb/master/README.md
- import: go.linka.cloud/protofilters
  repository: github.com/linka-cloud/protofilters
  readme: https://raw.githubusercontent.com/linka-cloud/protofilters/master/README.md
- import: go.linka.cloud/protoc-gen-go-fields
  repository: github.com/linka-cloud/protoc-gen-go-fields
  readme: https://raw.githubusercontent.com/linka-cloud/protoc-gen-go-fields/master/README.md
- import: go.linka.cloud/protoc-gen-defaults
  repository: github.com/linka-cloud/protoc-gen-defaults
  readme: https://raw.githubusercontent.com/linka-cloud/protoc-gen-defaults/master/README.md
- import: go.linka.cloud/grpc
  repository: github.com/linka-cloud/grpc
  readme: https://raw.githubusercontent.com/linka-cloud/grpc/master/README.md
- import: go.linka.cloud/protodb
  repository: github.com/linka-cloud/protodb
  readme: https://raw.githubusercontent.com/linka-cloud/protodb/master/README.md
- import: go.linka.cloud/go-repo
  repository: github.com/linka-cloud/go-repo
  readme: https://raw.githubusercontent.com/linka-cloud/go-repo/master/README.md
- import: go.linka.cloud/oidc-handlers
  repository: github.com/linka-cloud/oidc-handlers
  readme: https://raw.githubusercontent.com/linka-cloud/oidc-handlers/master/README.md
